// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: mapdata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gbid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group int32 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Type  int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Gbid) Reset() {
	*x = Gbid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gbid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gbid) ProtoMessage() {}

func (x *Gbid) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gbid.ProtoReflect.Descriptor instead.
func (*Gbid) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{0}
}

func (x *Gbid) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Gbid) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ExtraMarkerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GizmoType  *int32 `protobuf:"varint,1,opt,name=gizmoType,proto3,oneof" json:"gizmoType,omitempty"`
	MarkerType *int32 `protobuf:"varint,2,opt,name=markerType,proto3,oneof" json:"markerType,omitempty"`
	SpawnLoc   *Gbid  `protobuf:"bytes,3,opt,name=spawnLoc,proto3,oneof" json:"spawnLoc,omitempty"`
	Bounds     *AABB  `protobuf:"bytes,4,opt,name=bounds,proto3,oneof" json:"bounds,omitempty"`
}

func (x *ExtraMarkerData) Reset() {
	*x = ExtraMarkerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtraMarkerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraMarkerData) ProtoMessage() {}

func (x *ExtraMarkerData) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraMarkerData.ProtoReflect.Descriptor instead.
func (*ExtraMarkerData) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{1}
}

func (x *ExtraMarkerData) GetGizmoType() int32 {
	if x != nil && x.GizmoType != nil {
		return *x.GizmoType
	}
	return 0
}

func (x *ExtraMarkerData) GetMarkerType() int32 {
	if x != nil && x.MarkerType != nil {
		return *x.MarkerType
	}
	return 0
}

func (x *ExtraMarkerData) GetSpawnLoc() *Gbid {
	if x != nil {
		return x.SpawnLoc
	}
	return nil
}

func (x *ExtraMarkerData) GetBounds() *AABB {
	if x != nil {
		return x.Bounds
	}
	return nil
}

type MarkerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefSnoGroup       int32            `protobuf:"varint,1,opt,name=refSnoGroup,proto3" json:"refSnoGroup,omitempty"`
	RefSno            int32            `protobuf:"varint,2,opt,name=refSno,proto3" json:"refSno,omitempty"`
	SourceSno         int32            `protobuf:"varint,3,opt,name=sourceSno,proto3" json:"sourceSno,omitempty"`
	DataSnos          []int32          `protobuf:"varint,4,rep,packed,name=dataSnos,proto3" json:"dataSnos,omitempty"`
	Position          *Point3D         `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Extra             *ExtraMarkerData `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty"`
	MarkerHash        *uint32          `protobuf:"varint,10,opt,name=markerHash,proto3,oneof" json:"markerHash,omitempty"`
	MarkerGroupHashes []uint32         `protobuf:"varint,11,rep,packed,name=markerGroupHashes,proto3" json:"markerGroupHashes,omitempty"`
}

func (x *MarkerData) Reset() {
	*x = MarkerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerData) ProtoMessage() {}

func (x *MarkerData) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerData.ProtoReflect.Descriptor instead.
func (*MarkerData) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{2}
}

func (x *MarkerData) GetRefSnoGroup() int32 {
	if x != nil {
		return x.RefSnoGroup
	}
	return 0
}

func (x *MarkerData) GetRefSno() int32 {
	if x != nil {
		return x.RefSno
	}
	return 0
}

func (x *MarkerData) GetSourceSno() int32 {
	if x != nil {
		return x.SourceSno
	}
	return 0
}

func (x *MarkerData) GetDataSnos() []int32 {
	if x != nil {
		return x.DataSnos
	}
	return nil
}

func (x *MarkerData) GetPosition() *Point3D {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MarkerData) GetExtra() *ExtraMarkerData {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *MarkerData) GetMarkerHash() uint32 {
	if x != nil && x.MarkerHash != nil {
		return *x.MarkerHash
	}
	return 0
}

func (x *MarkerData) GetMarkerGroupHashes() []uint32 {
	if x != nil {
		return x.MarkerGroupHashes
	}
	return nil
}

type Point2D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point2D) Reset() {
	*x = Point2D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2D) ProtoMessage() {}

func (x *Point2D) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point2D.ProtoReflect.Descriptor instead.
func (*Point2D) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{3}
}

func (x *Point2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Point3D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Point3D) Reset() {
	*x = Point3D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point3D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point3D) ProtoMessage() {}

func (x *Point3D) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point3D.ProtoReflect.Descriptor instead.
func (*Point3D) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{4}
}

func (x *Point3D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point3D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point3D) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Bounds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Bounds) Reset() {
	*x = Bounds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bounds) ProtoMessage() {}

func (x *Bounds) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bounds.ProtoReflect.Descriptor instead.
func (*Bounds) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{5}
}

func (x *Bounds) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Bounds) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AABB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset *Point3D `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Ext    *Point3D `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *AABB) Reset() {
	*x = AABB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AABB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AABB) ProtoMessage() {}

func (x *AABB) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AABB.ProtoReflect.Descriptor instead.
func (*AABB) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{6}
}

func (x *AABB) GetOffset() *Point3D {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *AABB) GetExt() *Point3D {
	if x != nil {
		return x.Ext
	}
	return nil
}

type Polygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertices []*Point2D `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{7}
}

func (x *Polygon) GetVertices() []*Point2D {
	if x != nil {
		return x.Vertices
	}
	return nil
}

type MapData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GridSize      float32       `protobuf:"fixed32,1,opt,name=gridSize,proto3" json:"gridSize,omitempty"`
	Bounds        *Bounds       `protobuf:"bytes,2,opt,name=bounds,proto3" json:"bounds,omitempty"`
	ZoneArtScale  float32       `protobuf:"fixed32,3,opt,name=zoneArtScale,proto3" json:"zoneArtScale,omitempty"`
	ZoneArtCenter *Point2D      `protobuf:"bytes,4,opt,name=zoneArtCenter,proto3" json:"zoneArtCenter,omitempty"`
	MaxNativeZoom uint32        `protobuf:"varint,5,opt,name=maxNativeZoom,proto3" json:"maxNativeZoom,omitempty"`
	Markers       []*MarkerData `protobuf:"bytes,6,rep,name=markers,proto3" json:"markers,omitempty"`
	Polygons      []*Polygon    `protobuf:"bytes,7,rep,name=polygons,proto3" json:"polygons,omitempty"`
}

func (x *MapData) Reset() {
	*x = MapData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapdata_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_mapdata_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_mapdata_proto_rawDescGZIP(), []int{8}
}

func (x *MapData) GetGridSize() float32 {
	if x != nil {
		return x.GridSize
	}
	return 0
}

func (x *MapData) GetBounds() *Bounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *MapData) GetZoneArtScale() float32 {
	if x != nil {
		return x.ZoneArtScale
	}
	return 0
}

func (x *MapData) GetZoneArtCenter() *Point2D {
	if x != nil {
		return x.ZoneArtCenter
	}
	return nil
}

func (x *MapData) GetMaxNativeZoom() uint32 {
	if x != nil {
		return x.MaxNativeZoom
	}
	return 0
}

func (x *MapData) GetMarkers() []*MarkerData {
	if x != nil {
		return x.Markers
	}
	return nil
}

func (x *MapData) GetPolygons() []*Polygon {
	if x != nil {
		return x.Polygons
	}
	return nil
}

var File_mapdata_proto protoreflect.FileDescriptor

var file_mapdata_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x70, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x30, 0x0a, 0x04, 0x47, 0x62, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0xda, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x74, 0x72, 0x61, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x09, 0x67, 0x69, 0x7a, 0x6d, 0x6f, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x09, 0x67, 0x69, 0x7a, 0x6d,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0a,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a,
	0x08, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4c, 0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x47, 0x62, 0x69, 0x64, 0x48, 0x02, 0x52, 0x08, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4c,
	0x6f, 0x63, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x41, 0x41, 0x42, 0x42, 0x48, 0x03, 0x52, 0x06,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x67, 0x69,
	0x7a, 0x6d, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x70, 0x61, 0x77, 0x6e,
	0x4c, 0x6f, 0x63, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x22, 0xb0,
	0x02, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x65, 0x66, 0x53, 0x6e, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x53, 0x6e, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x53, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x66, 0x53, 0x6e, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x53, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x53, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x6e, 0x6f,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x6e, 0x6f,
	0x73, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x64, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12,
	0x23, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x61, 0x73,
	0x68, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x11, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x25, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x64, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x33, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x33, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12,
	0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x24, 0x0a,
	0x06, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x79, 0x22, 0x44, 0x0a, 0x04, 0x41, 0x41, 0x42, 0x42, 0x12, 0x20, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x33, 0x64, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a,
	0x03, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x33, 0x64, 0x52, 0x03, 0x65, 0x78, 0x74, 0x22, 0x2f, 0x0a, 0x07, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x64,
	0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x22, 0x8d, 0x02, 0x0a, 0x07, 0x4d,
	0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x67, 0x72, 0x69, 0x64, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x06, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x7a, 0x6f, 0x6e, 0x65, 0x41, 0x72, 0x74, 0x53, 0x63,
	0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x7a, 0x6f, 0x6e, 0x65, 0x41,
	0x72, 0x74, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x0d, 0x7a, 0x6f, 0x6e, 0x65, 0x41,
	0x72, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x64, 0x52, 0x0d, 0x7a, 0x6f, 0x6e, 0x65, 0x41, 0x72,
	0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x4e, 0x61,
	0x74, 0x69, 0x76, 0x65, 0x5a, 0x6f, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d,
	0x6d, 0x61, 0x78, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5a, 0x6f, 0x6f, 0x6d, 0x12, 0x25, 0x0a,
	0x07, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x52, 0x08, 0x70, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x73, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x6b, 0x6f, 0x74, 0x61, 0x36,
	0x32, 0x38, 0x2f, 0x64, 0x34, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapdata_proto_rawDescOnce sync.Once
	file_mapdata_proto_rawDescData = file_mapdata_proto_rawDesc
)

func file_mapdata_proto_rawDescGZIP() []byte {
	file_mapdata_proto_rawDescOnce.Do(func() {
		file_mapdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapdata_proto_rawDescData)
	})
	return file_mapdata_proto_rawDescData
}

var file_mapdata_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mapdata_proto_goTypes = []interface{}{
	(*Gbid)(nil),            // 0: Gbid
	(*ExtraMarkerData)(nil), // 1: ExtraMarkerData
	(*MarkerData)(nil),      // 2: MarkerData
	(*Point2D)(nil),         // 3: Point2d
	(*Point3D)(nil),         // 4: Point3d
	(*Bounds)(nil),          // 5: Bounds
	(*AABB)(nil),            // 6: AABB
	(*Polygon)(nil),         // 7: Polygon
	(*MapData)(nil),         // 8: MapData
}
var file_mapdata_proto_depIdxs = []int32{
	0,  // 0: ExtraMarkerData.spawnLoc:type_name -> Gbid
	6,  // 1: ExtraMarkerData.bounds:type_name -> AABB
	4,  // 2: MarkerData.position:type_name -> Point3d
	1,  // 3: MarkerData.extra:type_name -> ExtraMarkerData
	4,  // 4: AABB.offset:type_name -> Point3d
	4,  // 5: AABB.ext:type_name -> Point3d
	3,  // 6: Polygon.vertices:type_name -> Point2d
	5,  // 7: MapData.bounds:type_name -> Bounds
	3,  // 8: MapData.zoneArtCenter:type_name -> Point2d
	2,  // 9: MapData.markers:type_name -> MarkerData
	7,  // 10: MapData.polygons:type_name -> Polygon
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_mapdata_proto_init() }
func file_mapdata_proto_init() {
	if File_mapdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gbid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtraMarkerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point2D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point3D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bounds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AABB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Polygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapdata_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mapdata_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_mapdata_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapdata_proto_goTypes,
		DependencyIndexes: file_mapdata_proto_depIdxs,
		MessageInfos:      file_mapdata_proto_msgTypes,
	}.Build()
	File_mapdata_proto = out.File
	file_mapdata_proto_rawDesc = nil
	file_mapdata_proto_goTypes = nil
	file_mapdata_proto_depIdxs = nil
}
